version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: 'arn:aws:ecs:ap-northeast-2:ACCOUNT_ID:task-definition/prod-elicerracer'
        LoadBalancerInfo:
          ContainerName: 'elicerracer'
          ContainerPort: 3000
